return {}
-- return {
--   "hkupty/iron.nvim",
--   config = function()
--     local iron = require("iron.core")
--     local view = require("iron.view")
--     local common = require("iron.fts.common")
--
--     iron.setup({
--       config = {
--         -- Whether a repl should be discarded or not
--         scratch_repl = true,
--         -- Your repl definitions come here
--         repl_definition = {
--           sh = {
--             -- Can be a table or a function that
--             -- returns a table (see below)
--             command = { "zsh" },
--           },
--           python = {
--             command = { "python3" },  -- or { "ipython", "--no-autoindent" }
--             format = common.bracketed_paste_python,
--             block_dividers = { "# %%", "#%%" },
--             env = {PYTHON_BASIC_REPL = "0"} --this is needed for python3.13 and up.
--           }
--         },
--         -- How the repl window will be displayed
--         -- See below for more information
--         repl_open_cmd = view.split.vertical.rightbelow("%40"),
--       },
--       -- Iron doesn't set keymaps by default anymore.
--       -- You can set them here or manually add keymaps to the functions in iron.core
--       keymaps = {
--         send_motion = "<space>sc",
--         visual_send = "<space>sc",
--         send_file = "<space>sf",
--         send_line = "<space>sl",
--         send_paragraph = "<space>sp",
--         send_mark = "<space>sm",
--         send_code_block = "<space>sb",
--         send_code_block_and_move = "<space>sn",
--         mark_motion = "<space>mc",
--         mark_visual = "<space>mc",
--         remove_mark = "<space>md",
--         cr = "<space>s<cr>",
--         interrupt = "<space>s<space>",
--         exit = "<space>sq",
--         clear = "<space>cl",
--       },
--       -- If the highlight is on, you can change how it looks
--       -- For the available options, check nvim_set_hl
--       highlight = {
--         italic = false,
--       },
--       ignore_blank_lines = true, -- ignore blank lines when sending visual select lines
--     })
--
--     -- iron also has a list of commands, see :h iron-commands for all available commands
--     vim.keymap.set("n", "<space>rs", "<cmd>IronRepl<cr>")
--     vim.keymap.set("n", "<space>rr", "<cmd>IronRestart<cr>")
--     vim.keymap.set("n", "<space>rf", "<cmd>IronFocus<cr>")
--     vim.keymap.set("n", "<space>rh", "<cmd>IronHide<cr>")
--   end,
-- }
